apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  containers:
  - env:
    - name: MYSQL_DATABASE
      value: myproject2
    - name: MYSQL_PASSWORD
      value: admin
    - name: MYSQL_ROOT_PASSWORD
      value: admin
    - name: MYSQL_USER
      value: admin
    image: mariadb
    name: db
    ports:
    - containerPort: 3306
    resources: {}
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: db-claim0
  restartPolicy: OnFailure
  volumes:
  - name: db-claim0
    persistentVolumeClaim:
      claimName: db-claim0
status: {}
