# Generated by Django 3.1.1 on 2022-12-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='Логин')),
                ('second_name', models.CharField(max_length=15, verbose_name='Пароль')),
                ('phonenumber', models.CharField(max_length=12, unique=True, verbose_name='Номер')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Аккаунт участника',
                'verbose_name_plural': 'Аккаунты участников',
            },
        ),
    ]
